USE [master]
GO

/****** Object:  Database [Cespedes.Dylan.Parcial]    Script Date: 2/7/2024 11:11:50 ******/
CREATE DATABASE [Cespedes.Dylan.Parcial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cespedes.Dylan.Parcial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Cespedes.Dylan.Parcial.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cespedes.Dylan.Parcial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Cespedes.Dylan.Parcial_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cespedes.Dylan.Parcial].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET ARITHABORT OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET RECOVERY FULL 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET  MULTI_USER 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Cespedes.Dylan.Parcial] SET  READ_WRITE 
GO

